created project's skeleton code base
sachinrath1986/holdings pull request #2
Opened 2021-07-26 07:45 UTC by vivek-reddy-1234

2021-07-27 08:20 UTC, wissenshakti requested changes
Had some minor comments . @sachinrath1986  @vivek-reddy-1234  Please take a look and we can discuss further to resolve those or not

2021-07-27 08:20 UTC, wissenshakti commented on package.json
> +  "name": "photo-gallery",
need to change this to appropriate project name  . @sachinrath1986  how about wissenPortfolioApp ?

2021-07-27 08:20 UTC, wissenshakti commented on package.json
> +  "description": "An Ionic project"
Need to change the description to appropriate one. Ex: A Portfolio application skeleton to get quickly start with portfolio managment application.

2021-07-27 08:20 UTC, wissenshakti commented on public/index.html
> +    <title>Ionic App</title>
Change the title to Wissen Portfolio App

2021-07-27 12:07 UTC, sachinrath1986 commented on ionic.config.json
> +  "name": "photo-gallery",
name!

2021-07-27 12:34 UTC, wissenshakti commented
Commit message should include id of issue for ex : ' #1 some minor change' . Also commit message should not be vague
ex instead of your last commit ' #1 Address comments to conform with style guide' . Please edit the last commit to include github id

2021-08-02 15:58 UTC, sachinrath1986 commented
Merging for now. We can revisit the change requested later.

2021-08-02 15:58 UTC, merged