Created login screen
sachinrath1986/holdings pull request #8
Opened 2021-08-05 09:12 UTC by vivek-reddy-1234

Created login screen with Email and Password fields and styles

2021-08-05 09:52 UTC, wissenshakti requested changes

2021-08-05 09:52 UTC, wissenshakti commented on src/pages/LoginPage.css
> +    --checkmark-width: 3px;
use rem instead of px everywhere . 16px = 1 rem

2021-08-05 09:52 UTC, wissenshakti commented on src/pages/LoginPage.css
> +ion-grid.tc-check-grid {
use terms instead of tc

2021-08-05 11:45 UTC, sachinrath1986 commented on src/pages/LoginPage.css
> +    --bkgrd-blue: rgb(18, 18, 90);
try for hex code

2021-08-11 14:44 UTC, sachinrath1986 approved these changes

2021-08-15 15:54 UTC, sachinrath1986 approved these changes

2021-08-15 15:55 UTC, merged